// <auto-generated />
using System;
using Education.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Education.Persistence.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    partial class EducationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Education.Domain.Curso", b =>
                {
                    b.Property<Guid>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = new Guid("7cb0bdca-5964-447d-a427-a3283102642c"),
                            Description = "Curso C# basico",
                            FechaCreacion = new DateTime(2022, 9, 8, 22, 45, 3, 186, DateTimeKind.Local).AddTicks(9543),
                            FechaPublicacion = new DateTime(2024, 9, 8, 22, 45, 3, 186, DateTimeKind.Local).AddTicks(9554),
                            Precio = 56m,
                            Titulo = "C# Desde cero a master"
                        },
                        new
                        {
                            CursoId = new Guid("8401c60f-422f-477c-8d6a-ab9e2716000c"),
                            Description = "Curso java",
                            FechaCreacion = new DateTime(2022, 9, 8, 22, 45, 3, 186, DateTimeKind.Local).AddTicks(9577),
                            FechaPublicacion = new DateTime(2024, 9, 8, 22, 45, 3, 186, DateTimeKind.Local).AddTicks(9578),
                            Precio = 25m,
                            Titulo = "Master en Java desde las raices"
                        },
                        new
                        {
                            CursoId = new Guid("50b63f8e-c014-4619-bdbf-3808147b1d5a"),
                            Description = "Curso c# prubas unitarias",
                            FechaCreacion = new DateTime(2022, 9, 8, 22, 45, 3, 186, DateTimeKind.Local).AddTicks(9585),
                            FechaPublicacion = new DateTime(2024, 9, 8, 22, 45, 3, 186, DateTimeKind.Local).AddTicks(9586),
                            Precio = 1000m,
                            Titulo = "Master en pruebas unitarias"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
